### ISSUE TITLE
Write scraper to get zipcode's time zone from chabad.org html

### ISSUE THREAD

**Issue by kagan770** [Yossi/omer#15]
Here's the link to USPS zip code validator:
https://tools.usps.com/go/ZipLookupAction!input.action

Perhaps we can store the valid zip codes in order to minimize the call to USPS.  Once valid it "most likely" will be valid for the lifetime of US I assume.

Maybe even better if we will use the following cheatsheet:
http://www.cexx.org/zipcode.htm

**Comment by Yossi** [comment]
I've made changes to the program and now it will cache (in mysql) zipcodes once seen and will no longer look up what timezone they are in each time.

**Comment by Yossi** [comment]
I've noticed that chabad.org actually provides the timezone the zipcode is in, but only over HTML and not RSS for some annoying reason. 
Might be best to just write a scraper and offload all zipcode work to chabad.org

**Comment by Yossi** [comment]
this issue is mooted by using dateutil.tz.getz.

see util.py in the pythonanywhere branch
